config/routes.rb
Rails.application.routes.draw do
  get 'attractions/index'
  root "sessions#index"

  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :show, :create]

  resources :attractions, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  resources :rides
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_many :rides
  has_many :users, through: :rides
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  belongs_to :attraction

  def take_ride
    user = User.find(user_id)
    attraction = Attraction.find(attraction_id)
    result = []
    final = ""

    # tickets
    user_tickets = user.tickets
    attraction_tickets = attraction.tickets

    # height
    user_height = user.height
    attraction_min_height = attraction.min_height

    # happiness
    user_happiness = user.happiness
    attraction_happiness_rating = attraction.happiness_rating

    # nausea
    user_nausea = user.nausea
    attraction_nausea_rating = attraction.nausea_rating

    if enough_tickets?(user_tickets, attraction_tickets)
    else
      result << "You do not have enough tickets to ride the #{attraction.name}."
    end

    if tall_enough?(user_height, attraction_min_height)
    else
      result << "You are not tall enough to ride the #{attraction.name}."
    end

    if result.size > 0
      result = result.unshift("Sorry.")
      final = result.join(" ")
    else
      updated_user_tickets = (user_tickets.to_i - attraction_tickets.to_i)
      updated_user_happiness = (user_happiness.to_i + attraction_happiness_rating.to_i)
      updated_user_nausea = (user_nausea.to_i + attraction_nausea_rating.to_i)

      user.update(tickets: updated_user_tickets, nausea: updated_user_nausea, happiness: updated_user_happiness)
    end

    final
  end

  def tall_enough?(user_height, attraction_height)
    user_height >= attraction_height ? true : false
  end
  
  def enough_tickets?(user_tickets, attraction_tickets)
    user_tickets >= attraction_tickets ? true : false
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :rides
  has_many :attractions, through: :rides

  validates :name,
    presence: true,
    uniqueness: true, 
    on: :create

  validates :password,
    presence: true,
    on: :create

  def mood
    # if the user is more nauseous than happy
    mood = "okay"
    if happiness > nausea
      mood = "happy"
    elsif nausea > happiness
      mood = "sad"
    end
    mood
  end

  def user_type
    self.admin ? "ADMIN" : "USER"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user, :admin?

  def authentication_required
    if !logged_in?
      redirect_to root_path
    end
  end

  def admin?
    current_user.admin
  end

  def logged_in?
    current_user != nil
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  def index
    @attractions = Attraction.all
  end

  def show
    @attraction = Attraction.find(params[:id])
    @ride = Ride.new
  end

  def new
    @attraction = Attraction.new
  end

  def create
    @attraction = Attraction.new(attraction_params)

    if @attraction.save
      flash[:notice] = "New attraction added."
      redirect_to attraction_path(@attraction)
    else
      render :new
    end
  end

  def edit
    @attraction = Attraction.find(params[:id])
  end

  def update
    @attraction = Attraction.find(params[:id])

    if @attraction.update_attributes(attraction_params)
      flash[:notice] = "Attraction updated."
      redirect_to attraction_path(@attraction)
    else
      render :edit
    end
  end

  def destroy
    @attraction = Attraction.find(params[:id])
  end

  private

  def attraction_params
    params.require(:attraction).permit(:name, :tickets, :nausea_rating, :happiness_rating, :min_height)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def create
    @ride = Ride.new(ride_params)
    ride_result = @ride.take_ride

    if ride_result.empty? && @ride.save
      flash[:notice] = "Thanks for riding the #{Attraction.find(params[:ride][:attraction_id]).name}!"
      redirect_to user_path(User.find(params[:ride][:user_id]))
    else
      flash[:notice] = ride_result
      redirect_to user_path(User.find(params[:ride][:user_id]))
    end
  end

  private

  def ride_params
    params.require(:ride).permit(:user_id, :attraction_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
    @users = User.all
  end

  def create
    user = User.find_by(name: params[:user_name])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authentication_required, except: [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :height, :happiness, :nausea, :tickets, :password, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render partial: 'application/error_messages', locals: { object: object }
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
  def tall_enough?(user_height, attraction_height)
    user_height >= attraction_height ? true : false
  end
  
  def enough_tickets?(user_tickets, attraction_tickets)
    user_tickets >= attraction_tickets ? true : false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div class="container">
    <div class="row mb-3">
      <div class="col">
        <div id="error-explanation">
          <h4>
            <%= pluralize(object.errors.size, "error") %> prevented this record from being saved.
          </h4>
          <p>The following fields have problems:</p>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li class="text-danger">
                <%= msg %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/attractions/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Please enter a name" %>
</div>

<div class="form-group">
  <%= f.label :min_height %>
  <%= f.text_field :min_height, class: "form-control", placeholder: "Please enter a minimum height" %>
</div>

<div class="form-group">
  <%= f.label :happiness_rating %>
  <%= f.text_field :happiness_rating, class: "form-control", placeholder: "Please enter a happiness rating" %>
</div>

<div class="form-group">
  <%= f.label :nausea_rating %>
  <%= f.text_field :nausea_rating, class: "form-control", placeholder: "Please enter a nausea rating" %>
</div>

<div class="form-group">
  <%= f.label :tickets %>
  <%= f.text_field :tickets, class: "form-control", placeholder: "Please enter a tickets" %>
</div>

<div class="form-group mt-3">
  <%= f.submit submit_text, class: "btn btn-primary" %>
</div>

app/views/attractions/edit.html.erb
<div class="row mt-5">
  <div class="col">
    <h3>Edit Attraction</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%= form_for @attraction do |f| %>
      <%= render partial: "form", locals: { f: f, submit_text: "Update Attraction" } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

app/views/attractions/index.html.erb
<div class="row mt-4">
  <div class="col">
    <h3>All Attractions</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<% if admin? %>

<div class="row">
  <div class="col">
    <%= link_to "new attraction", new_attraction_path %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<% end %>

<div class="row">
  <div class="col">
    <ul>
      <% @attractions.each do |attraction| %>
        <li>
          <% if admin? %>
            <%= link_to "Show #{attraction.name}", attraction_path(attraction) %> - <%= link_to "edit", edit_attraction_path(attraction) %> - <%= link_to "delete", attraction, method: :delete, data: { confirm: "Are you sure?" } %>
          <% else %>
            <%= link_to "Go on #{attraction.name}", attraction_path(attraction) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

app/views/attractions/new.html.erb
<div class="row mt-5">
  <div class="col">
    <h3>New Attraction</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%= form_for @attraction do |f| %>
      <%= render partial: "form", locals: { f: f, submit_text: "Create Attraction" } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

app/views/attractions/show.html.erb
<div class="row mt-4">
  <div class="col">
    <h3><%= @attraction.name %></h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= link_to "<< all attraction", attractions_path %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<% if admin? %>

<div class="row">
  <div class="col">
    <%= link_to "Edit Attraction", edit_attraction_path(@attraction) %> | <%= link_to "delete", @attraction, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<% end %>

<div class="row">
  <div class="col">
    <p>
      Tickets: <%= @attraction.tickets %>
    </p>
    <p>
      Nausea Rating: <%= @attraction.nausea_rating %>
    </p>
    <p>
      Happiness Rating: <%= @attraction.happiness_rating %>
    </p>
    <p>
      Minimum Height: <%= @attraction.min_height %>
    </p>
  </div>
</div>

<% unless admin? %>
  <div class="row">
    <div class="col">
      <%= form_for @ride do |f| %>
        <%= f.hidden_field :user_id, value: "#{current_user.id}" %>
        <%= f.hidden_field :attraction_id, value: "#{@attraction.id}" %>
        <%= f.submit "Go on this ride", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav id="main-navigation" class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Rails Amusement Park</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Log Out", logout_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "User Info", user_path(session[:user_id]), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "See attractions", attractions_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", signin_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <h6 class="text-white mr-3">mood <span class="badge badge-primary"><%= current_user.mood %></span></h6> 
          <h6 class="text-white mr-3">happiness <span class="badge badge-primary"><%= current_user.happiness %></span></h6> 
          <h6 class="text-white mr-3">nausea <span class="badge badge-primary"><%= current_user.nausea %></span></h6> 
          <h6 class="text-white mr-3">height <span class="badge badge-primary"><%= current_user.height %></span></h6> 
          <h6 class="text-white mr-5">tickets <span class="badge badge-primary"><%= current_user.tickets %></span></h6>        
          <h6 class="text-white"><span class="badge badge-info"><%= current_user.user_type %></span></%=> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if !flash[:notice].blank? %>
  <div class="container">
    <div class="row mt-4">
      <div class="col">
        <%= flash[:notice] %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeJune2019RailsAmusementPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navigation" %>

    <%= render partial: "layouts/notice" %>

    <div class="container" role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Please enter a name" %>
</div>

<div class="form-group">
  <%= f.label :height %>
  <%= f.text_field :height, class: "form-control", placeholder: "Please enter a height" %>
</div>

<div class="form-group">
  <%= f.label :happiness %>
  <%= f.text_field :happiness, class: "form-control", placeholder: "Please enter a happiness" %>
</div>

<div class="form-group">
  <%= f.label :nausea %>
  <%= f.text_field :nausea, class: "form-control", placeholder: "Please enter a nausea" %>
</div>

<div class="form-group">
  <%= f.label :tickets %>
  <%= f.text_field :tickets, class: "form-control", placeholder: "Please enter a tickets" %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", placeholder: "Please enter a password" %>
</div>

<div class="form-check">
  <%= f.check_box :admin, class: "form-check-input" %>
  <%= f.label :admin, class: "form-check-label"%>
</div>

<div class="form-group mt-3">
  <%= f.submit submit_text, class: "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="row mt-5">
  <div class="col">
    <h3>Sign Up</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%= form_for @user do |f| %>
      <%= render partial: "form", locals: { f: f, submit_text: "Create User" } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

app/views/users/show.html.erb
<div class="row mt-5">
  <div class="col">
    <h3>User Details</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row">
  <div class="col">
    Name: <%= @user.name %>
  </div>
</div>

<div class="row">
  <div class="col">
    User Type: <%= @user.user_type %>
  </div>
</div>

<div class="row">
  <div class="col">
    Height: <%= @user.height %>
  </div>
</div>

<div class="row">
  <div class="col">
    Tickets: <%= @user.tickets %>
  </div>
</div>

<div class="row">
  <div class="col">
    Happiness: <%= @user.happiness %>
  </div>
</div>

<div class="row">
  <div class="col">
    Nausea: <%= @user.nausea %>
  </div>
</div>

<div class="row">
  <div class="col">
    Mood: <%= @user.mood %>
  </div>
</div>